# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 11:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_uri', models.CharField(max_length=40)),
                ('managed_resource_uri', models.CharField(max_length=40)),
                ('message_text', models.CharField(max_length=500)),
                ('message_title', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('modified_at', models.DateTimeField(default=datetime.datetime.now)),
                ('created_by', models.CharField(max_length=40)),
                ('modified_by', models.CharField(max_length=40)),
            ],
        ),
    ]
